### ISSUE TITLE
pre_train model

### ISSUE THREAD

**Issue by world2025** [MLEnthusiast/MHCLN#2]
hello, thx for your open source, but I meet a problem, when I use the extract_features.py file for UCMD dataset, the error is ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4\udcceļ\udcfe\udca1\udca3
; No such file or directory
for the pretrain_model, but I download the inception_v3.ckpt pretrain_model
can you tell me how to fix it ?thx

**Comment by tkone2018** [comment]
ok,i solve it
